### ISSUE TITLE
Diffusers implementation for the attention mask workflow?

### ISSUE THREAD

**Issue by emilyo9264** [cubiq/Diffusers_IPAdapter#4]
Hey great repo! I came across your comfyui workflow using attention mask (or multiple masks for different regions). Wondering if this would be implemented for diffusers as well? If not, would you mind providing some hints on how I can connect attention masks to ip adapters? Thanks!

**Comment by cubiq** [comment]
diffusers now supports IPAdapter internally but at the moment they don't seem interested in implementing features other the official ones. I offered to work on the missing features but it seems a very slow clog (of course it's a big project, they have QC). So I'm a bit uncertain if I should keep working on this repo. I'll keep an eye on the official implementation and see how it goes.
