### ISSUE TITLE
AttributeError: 'IPAdapter' object has no attribute 'get_prompt_embeds'

### ISSUE THREAD

**Issue by Mr-Jin2** [cubiq/Diffusers_IPAdapter#6]
I can't find the attribute named get_prompt_embeds in ip_adapter.py, where is it

**Comment by cubiq** [comment]
You probably need to update the library

**Comment by Mr-Jin2** [comment]
Found the problem. Because the original ip_adapter package was already installed before, so the IPAdapter class from the original package was imported by default. Thank you for your reply.
